-- =========================================
-- Portfolio DB schema (PostgreSQL)

-- 1) Base tables


CREATE TABLE IF NOT EXISTS school (
  school_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  start_date DATE,
  end_date   DATE,
  status     VARCHAR(30),
  avg_grade  NUMERIC(3,2),

  CONSTRAINT uq_school_name UNIQUE (name),
  CONSTRAINT chk_school_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
  CONSTRAINT chk_school_avg_grade CHECK (avg_grade IS NULL OR (avg_grade >= 0 AND avg_grade <= 5))
);

CREATE TABLE IF NOT EXISTS diary (
  diary_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  title      VARCHAR(200) NOT NULL,
  slug       VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_diary_slug UNIQUE (slug),
  CONSTRAINT uq_diary_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tech (
  tech_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    VARCHAR(60) NOT NULL,

  CONSTRAINT uq_tech_name UNIQUE (name)
);

-- -----------------------------------------
-- 2) Core entities
-- -----------------------------------------

CREATE TABLE IF NOT EXISTS course (
  course_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(120) NOT NULL,
  start_date  DATE NOT NULL,
  end_date    DATE,
  school_id   INT NOT NULL,
  status      VARCHAR(30) NOT NULL,
  grade       VARCHAR(30),
  diary_id    INT,

  CONSTRAINT fk_course_school
    FOREIGN KEY (school_id) REFERENCES school(school_id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_course_diary
    FOREIGN KEY (diary_id) REFERENCES diary(diary_id)
    ON DELETE SET NULL,

  CONSTRAINT chk_course_dates CHECK (end_date IS NULL OR end_date >= start_date),
  CONSTRAINT chk_course_status CHECK (status IN ('planned', 'in_progress', 'completed'))
);

CREATE TABLE IF NOT EXISTS project (
  project_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(120) NOT NULL,
  start_date   DATE,
  end_date     DATE,
  school_id    INT,
  status       VARCHAR(30) NOT NULL,
  description  TEXT,
  github_url   TEXT,
  diary_id     INT,

  CONSTRAINT fk_project_school
    FOREIGN KEY (school_id) REFERENCES school(school_id)
    ON DELETE SET NULL,

  CONSTRAINT fk_project_diary
    FOREIGN KEY (diary_id) REFERENCES diary(diary_id)
    ON DELETE SET NULL,

  CONSTRAINT chk_project_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
  CONSTRAINT chk_project_status CHECK (status IN ('planned', 'in_progress', 'completed')),
  CONSTRAINT chk_project_github_url CHECK (
    github_url IS NULL OR (
      github_url ~ '^https://github[.]com/[A-Za-z0-9]([A-Za-z0-9-]{0,37}[A-Za-z0-9])?/[A-Za-z0-9._-]{1,100}$'
      AND github_url !~ '^https://github[.]com/[^/]*--'
      AND split_part(github_url, '/', 5) NOT IN ('.', '..')
    )
  )
);

-- -----------------------------------------
-- 3) M:N link tables
-- -----------------------------------------

-- Course <-> Project
CREATE TABLE IF NOT EXISTS course_projects (
  course_id      INT NOT NULL,
  project_id     INT NOT NULL,
  relation_type  VARCHAR(30),
  note           TEXT,

  CONSTRAINT pk_course_projects PRIMARY KEY (course_id, project_id),

  CONSTRAINT fk_course_projects_course
    FOREIGN KEY (course_id) REFERENCES course(course_id)
    ON DELETE CASCADE,

  CONSTRAINT fk_course_projects_project
    FOREIGN KEY (project_id) REFERENCES project(project_id)
    ON DELETE CASCADE
);

-- Project <-> Tech
CREATE TABLE IF NOT EXISTS project_tech (
  project_id  INT NOT NULL,
  tech_id     INT NOT NULL,
  usage_area  VARCHAR(30),
  note        TEXT,

  CONSTRAINT pk_project_tech PRIMARY KEY (project_id, tech_id),

  CONSTRAINT fk_project_tech_project
    FOREIGN KEY (project_id) REFERENCES project(project_id)
    ON DELETE CASCADE,

  CONSTRAINT fk_project_tech_tech
    FOREIGN KEY (tech_id) REFERENCES tech(tech_id)
    ON DELETE RESTRICT,

  CONSTRAINT chk_project_tech_usage CHECK (
    usage_area IS NULL OR usage_area IN ('frontend', 'backend', 'db', 'infra', 'ci', 'other')
  )
);

-- Course <-> Tech (requested)
CREATE TABLE IF NOT EXISTS course_tech (
  course_id  INT NOT NULL,
  tech_id    INT NOT NULL,
  emphasis   VARCHAR(30),
  note       TEXT,

  CONSTRAINT pk_course_tech PRIMARY KEY (course_id, tech_id),

  CONSTRAINT fk_course_tech_course
    FOREIGN KEY (course_id) REFERENCES course(course_id)
    ON DELETE CASCADE,

  CONSTRAINT fk_course_tech_tech
    FOREIGN KEY (tech_id) REFERENCES tech(tech_id)
    ON DELETE RESTRICT,

  CONSTRAINT chk_course_tech_emphasis CHECK (
    emphasis IS NULL OR emphasis IN ('main', 'secondary', 'optional')
  )
);

-- -----------------------------------------
-- 4) Helpful indexes
-- -----------------------------------------

-- Foreign-key lookups
CREATE INDEX IF NOT EXISTS idx_course_school_id ON course(school_id);
CREATE INDEX IF NOT EXISTS idx_course_diary_id  ON course(diary_id);

CREATE INDEX IF NOT EXISTS idx_project_school_id ON project(school_id);
CREATE INDEX IF NOT EXISTS idx_project_diary_id  ON project(diary_id);

-- Reverse lookups for link tables (useful in queries)
CREATE INDEX IF NOT EXISTS idx_course_projects_project_id ON course_projects(project_id);
CREATE INDEX IF NOT EXISTS idx_project_tech_tech_id       ON project_tech(tech_id);
CREATE INDEX IF NOT EXISTS idx_course_tech_tech_id        ON course_tech(tech_id);